// Limits LED strip power (percent [5% .. 100%])
#define DEFAULT_MAX_POWER 25

#define BUTTON_COMMAND_STEP_INTERVAL 200

#define BUTTON_COMMAND_NONE 0
#define BUTTON_COMMAND_STEP_BRIGHT 1
#define BUTTON_COMMAND_STEP_DIM 2
#define BUTTON_COMMAND_PRESET_COLORS 3
